# Project: Autoresolver
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"D:/Applications/WXDev-Cpp/Lib" -L"D:/Dev-Cpp/lib" -lwsock32  
INCS =  -I"D:/Applications/WXDev-Cpp/Include" 
CXXINCS =  -I"D:/Applications/WXDev-Cpp/lib/gcc/mingw32/3.4.5/include"  -I"D:/Applications/WXDev-Cpp/include/c++/3.4.5/backward"  -I"D:/Applications/WXDev-Cpp/include/c++/3.4.5/mingw32"  -I"D:/Applications/WXDev-Cpp/include/c++/3.4.5"  -I"D:/Applications/WXDev-Cpp/include"  -I"D:/Applications/WXDev-Cpp/"  -I"D:/Applications/WXDev-Cpp/include/common/wx/msw"  -I"D:/Applications/WXDev-Cpp/include/common/wx/generic"  -I"D:/Applications/WXDev-Cpp/include/common/wx/html"  -I"D:/Applications/WXDev-Cpp/include/common/wx/protocol"  -I"D:/Applications/WXDev-Cpp/include/common/wx/xml"  -I"D:/Applications/WXDev-Cpp/include/common/wx/xrc"  -I"D:/Applications/WXDev-Cpp/include/common/wx"  -I"D:/Applications/WXDev-Cpp/include/common" 
BIN  = Autoresolver.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Autoresolver.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Autoresolver.exe" $(LIBS)

main.o: main.cpp D:/Applications/WXDev-Cpp/include/c++/3.4.5/cstdlib   D:/Applications/WXDev-Cpp/include/c++/3.4.5/iostream   D:/Applications/WXDev-Cpp/include/c++/3.4.5/sstream   D:/Applications/WXDev-Cpp/include/c++/3.4.5/fstream
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
