# Project: AutoresolverMk2
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o Units.o InputCommands.o OutputFileCommands.o Combat.o InputFileCommands.o MagicCombat.o $(RES)
LINKOBJ  = main.o Units.o InputCommands.o OutputFileCommands.o Combat.o InputFileCommands.o MagicCombat.o $(RES)
LIBS =  -L"D:/Applications/WXDev-Cpp/Lib" -L"D:/Dev-Cpp/lib" -lwsock32  
INCS =  -I"D:/Applications/WXDev-Cpp/Include" 
CXXINCS =  -I"D:/Applications/WXDev-Cpp/lib/gcc/mingw32/3.4.5/include"  -I"D:/Applications/WXDev-Cpp/include/c++/3.4.5/backward"  -I"D:/Applications/WXDev-Cpp/include/c++/3.4.5/mingw32"  -I"D:/Applications/WXDev-Cpp/include/c++/3.4.5"  -I"D:/Applications/WXDev-Cpp/include"  -I"D:/Applications/WXDev-Cpp/"  -I"D:/Applications/WXDev-Cpp/include/common/wx/msw"  -I"D:/Applications/WXDev-Cpp/include/common/wx/generic"  -I"D:/Applications/WXDev-Cpp/include/common/wx/html"  -I"D:/Applications/WXDev-Cpp/include/common/wx/protocol"  -I"D:/Applications/WXDev-Cpp/include/common/wx/xml"  -I"D:/Applications/WXDev-Cpp/include/common/wx/xrc"  -I"D:/Applications/WXDev-Cpp/include/common/wx"  -I"D:/Applications/WXDev-Cpp/include/common" 
BIN  = AutoresolverMk2.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before AutoresolverMk2.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "AutoresolverMk2.exe" $(LIBS)

main.o: main.cpp Units.h   D:/Applications/WXDev-Cpp/include/c++/3.4.5/cstdlib   D:/Applications/WXDev-Cpp/include/c++/3.4.5/iostream   D:/Applications/WXDev-Cpp/include/c++/3.4.5/fstream   D:/Applications/WXDev-Cpp/include/windows.h   D:/Applications/WXDev-Cpp/include/c++/3.4.5/sstream
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Units.o: Units.cpp Units.h   D:/Applications/WXDev-Cpp/include/c++/3.4.5/cstdlib   D:/Applications/WXDev-Cpp/include/c++/3.4.5/iostream   D:/Applications/WXDev-Cpp/include/c++/3.4.5/fstream   D:/Applications/WXDev-Cpp/include/windows.h   D:/Applications/WXDev-Cpp/include/c++/3.4.5/sstream
	$(CPP) -c Units.cpp -o Units.o $(CXXFLAGS)

InputCommands.o: InputCommands.cpp Units.h   D:/Applications/WXDev-Cpp/include/c++/3.4.5/cstdlib   D:/Applications/WXDev-Cpp/include/c++/3.4.5/iostream   D:/Applications/WXDev-Cpp/include/c++/3.4.5/fstream   D:/Applications/WXDev-Cpp/include/windows.h   D:/Applications/WXDev-Cpp/include/c++/3.4.5/sstream
	$(CPP) -c InputCommands.cpp -o InputCommands.o $(CXXFLAGS)

OutputFileCommands.o: OutputFileCommands.cpp Units.h   D:/Applications/WXDev-Cpp/include/c++/3.4.5/cstdlib   D:/Applications/WXDev-Cpp/include/c++/3.4.5/iostream   D:/Applications/WXDev-Cpp/include/c++/3.4.5/fstream   D:/Applications/WXDev-Cpp/include/windows.h   D:/Applications/WXDev-Cpp/include/c++/3.4.5/sstream
	$(CPP) -c OutputFileCommands.cpp -o OutputFileCommands.o $(CXXFLAGS)

Combat.o: Combat.cpp Units.h   D:/Applications/WXDev-Cpp/include/c++/3.4.5/cstdlib   D:/Applications/WXDev-Cpp/include/c++/3.4.5/iostream   D:/Applications/WXDev-Cpp/include/c++/3.4.5/fstream   D:/Applications/WXDev-Cpp/include/windows.h   D:/Applications/WXDev-Cpp/include/c++/3.4.5/sstream
	$(CPP) -c Combat.cpp -o Combat.o $(CXXFLAGS)

InputFileCommands.o: InputFileCommands.cpp Units.h   D:/Applications/WXDev-Cpp/include/c++/3.4.5/cstdlib   D:/Applications/WXDev-Cpp/include/c++/3.4.5/iostream   D:/Applications/WXDev-Cpp/include/c++/3.4.5/fstream   D:/Applications/WXDev-Cpp/include/windows.h   D:/Applications/WXDev-Cpp/include/c++/3.4.5/sstream
	$(CPP) -c InputFileCommands.cpp -o InputFileCommands.o $(CXXFLAGS)

MagicCombat.o: MagicCombat.cpp Units.h   D:/Applications/WXDev-Cpp/include/c++/3.4.5/cstdlib   D:/Applications/WXDev-Cpp/include/c++/3.4.5/iostream   D:/Applications/WXDev-Cpp/include/c++/3.4.5/fstream   D:/Applications/WXDev-Cpp/include/windows.h   D:/Applications/WXDev-Cpp/include/c++/3.4.5/sstream
	$(CPP) -c MagicCombat.cpp -o MagicCombat.o $(CXXFLAGS)
