/*
  This file will be overwritten by wxDev-C++ at every compile.
  Do not edit this file as your changes will be lost.
  You can, however, include this file and use the defines.
*/
#ifndef AUTORESOLVER_PRIVATE_H
#define AUTORESOLVER_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"3.1.5.2"
#define VER_MAJOR	3
#define VER_MINOR	1
#define VER_RELEASE	5
#define VER_BUILD	2
#define COMPANY_NAME	""
#define FILE_VERSION	"3.1.5.0"
#define FILE_DESCRIPTION	"Galactic Nations Autoresolver"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"Galactic Nations Autoresolver"
#define PRODUCT_VERSION	""

#endif /*AUTORESOLVER_PRIVATE_H*/
